// Call the Email notification Generator with inputs. This willsend email to the approver in a cleaner HTML format
//return commerce.emailNotificationGenerator(_quote_process_submitted_by_submit_quote,_quote_process_submit_comment, level1ApprovalReason_quote, level1ApprovalReason_quote,level1Approver_quote ,linkToDocument_quote );

return commerce.newEmailNotificationGenerator(_quote_process_submitted_by_submit_quote,_quote_process_submit_comment, level1ApprovalReason_quote, level1ApprovalReason_quote,level1Approver_quote ,linkToDocument_quote );